# Generated by Django 3.0.7 on 2020-07-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200629_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
    ]
