# Generated by Django 3.0.7 on 2020-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200711_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vat',
            field=models.FloatField(choices=[(0, '0%'), (0.2, '20%'), (0.05, '5%')], default=0),
        ),
    ]
