# Generated by Django 3.0.7 on 2020-07-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vat_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
